### ISSUE TITLE
CLI documentation

### ISSUE THREAD

**Issue by sparcut** [jariz/scdl#3]
Yo.

Was a little confused at first since readme didn't have anything about CLI usage.

I found the options after looking through the `scdl-cli.coffee`, running the command without any options.

**Comment by jariz** [comment]
My presumption was that people would just run `scdl --help` and find out themselves, but it can't hurt to write the output down in the readme too for clarification.  
Is this OK? (see readme now)

**Comment by sparcut** [comment]
Yeah, that looks great.
Thanks dude.
